export type CreatureId =
  | 'egg'
  | 'blobby'
  | 'sunnling'
  | 'grumbit'
  | 'wisp'
  | 'puffi'
  | 'grimble'
  | 'lumix'
  | 'gloom'
  | 'phantom';

export interface CreatureData {
  id: CreatureId;
  name: string;
  description: string;
  palette: Record<string, string>;
  idleFrames: string[][];
  sleepFrames: string[][];
  eatFrames: string[][];
  happyFrames: string[][];
}

// ─── Palette conventions ─────────────────────────────────────────────────────
// Each sprite is 16×16 characters.  '.' = transparent.
// Every other char maps to an entry in that creature's `palette`.

const EGG: CreatureData = {
  id: 'egg', name: 'Egg', description: 'Something is stirring inside…',
  palette: {
    a: '#F5E6C8',   // cream body
    b: '#FDFAF2',   // highlight spot
    c: '#C8A060',   // shadow (bottom)
    d: '#7B4E1A',   // crack line
  },
  idleFrames: [
    [
      '................',
      '.....aaaaaa.....',
      '....aaaaaaaa....',
      '...aaabaaaaa....',
      '..aaabaaaaaaa...',
      '..aaaaaaaaaaaa..',
      '..adaaaaaaaaaa..',
      '..aadaaaaaaaaa..',
      '..acccccccaaa...',
      '..acccccccccaa..',
      '...acccccccca...',
      '....aaaaaaaa....',
      '.....aaaaaa.....',
      '................',
      '................',
      '................',
    ],
    [
      '................',
      '.....aaaaaa.....',
      '....aaaaaaaa....',
      '...aaabaaaaa....',
      '..aaabaaaaaaa...',
      '..aaaaaaaaaaaa..',
      '..adaaaaaaaaaa..',
      '..aaddaaaaaaaa..',
      '..acccccccaaa...',
      '..acccccccccaa..',
      '...acccccccca...',
      '....aaaaaaaa....',
      '.....aaaaaa.....',
      '................',
      '................',
      '................',
    ],
  ],
  sleepFrames: [[
    '................',
    '.....aaaaaa.....',
    '....aaaaaaaa....',
    '...aaaaaaaaaa...',
    '..aaaaaaaaaaaa..',
    '..aaaaaaaaaaaa..',
    '..aaaaaaaaaaaa..',
    '..aaaaaaaaaaaa..',
    '..acccccccaaaa..',
    '..accccccccca...',
    '...acccccccca...',
    '....aaaaaaaa....',
    '.....aaaaaa.....',
    '................',
    '................',
    '................',
  ]],
  eatFrames: [[
    '................',
    '.....aaaaaa.....',
    '....aaaaaaaa....',
    '...aaabaaaaa....',
    '..aaabaaaaaaa...',
    '..aaaaaaaaaaaa..',
    '..adaaaaaaaaaa..',
    '..aaaaaaaaaaaa..',
    '..acccccccaaa...',
    '..acccccccccaa..',
    '...acccccccca...',
    '....aaaaaaaa....',
    '.....aaaaaa.....',
    '................',
    '................',
    '................',
  ]],
  happyFrames: [[
    '................',
    '.....aaaaaa.....',
    '....aaaaaaaa....',
    '...aaabaaaaa....',
    '..aaabaaaaaaa...',
    '..aaaaaaaaaaaa..',
    '..adaaaaaaaaaa..',
    '..aaddaaaaaaaa..',
    '..acccccccaaa...',
    '..acccccccccaa..',
    '...acccccccca...',
    '....aaaaaaaa....',
    '.....aaaaaa.....',
    '................',
    '................',
    '................',
  ]],
};

const BLOBBY: CreatureData = {
  id: 'blobby', name: 'Blobby', description: 'A curious little blob. Always hungry.',
  palette: {
    b: '#FFD9A8',   // peach body
    e: '#2D2D2D',   // eye pupil
    m: '#FF7A7A',   // open mouth
    f: '#2D2D2D',   // closed-eye line (blink)
    r: '#FFAAAA',   // blush (unused here but reserved)
  },
  idleFrames: [
    // eyes open
    [
      '................',
      '....bbbbbb......',
      '...bbbbbbbb.....',
      '..bbbbbbbbbb....',
      '..beebbbbeebb...',
      '..beebbbbeebb...',
      '..bbbbbbbbbb....',
      '..bbbmmmbbbb....',
      '..bbbbbbbbbb....',
      '...bbbbbbbb.....',
      '....bbbbbb......',
      '.....bbbb.......',
      '................',
      '................',
      '................',
      '................',
    ],
    // blink
    [
      '................',
      '....bbbbbb......',
      '...bbbbbbbb.....',
      '..bbbbbbbbbb....',
      '..bffbbbbbffb...',
      '..bbbbbbbbbb....',
      '..bbbbbbbbbb....',
      '..bbbmmmbbbb....',
      '..bbbbbbbbbb....',
      '...bbbbbbbb.....',
      '....bbbbbb......',
      '.....bbbb.......',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
  sleepFrames: [[
    '................',
    '....bbbbbb......',
    '...bbbbbbbb.....',
    '..bbbbbbbbbb....',
    '..bffbbbbbffb...',
    '..bbbbbbbbbb....',
    '..bbbbbbbbbb....',
    '..bbbbbbbbbb....',
    '..bbbbbbbbbb....',
    '...bbbbbbbb.....',
    '....bbbbbb......',
    '.....bbbb.......',
    '................',
    '................',
    '................',
    '................',
  ]],
  eatFrames: [[
    '................',
    '....bbbbbb......',
    '...bbbbbbbb.....',
    '..bbbbbbbbbb....',
    '..beebbbbeebb...',
    '..beebbbbeebb...',
    '..bbbbbbbbbb....',
    '..bbmmmmmbbb....',
    '..bbbbbbbbbb....',
    '...bbbbbbbb.....',
    '....bbbbbb......',
    '.....bbbb.......',
    '................',
    '................',
    '................',
    '................',
  ]],
  happyFrames: [[
    '................',
    '....bbbbbb......',
    '...bbbbbbbb.....',
    '..bbbbbbbbbb....',
    '..beebbbbeebb...',
    '..beebbbbeebb...',
    '..bbbbbbbbbb....',
    '..bbbmmmbbbb....',
    '..bbbbbbbbbb....',
    '....bbbbbb......',
    '...b......b.....',
    '.....bbbb.......',
    '................',
    '................',
    '................',
    '................',
  ]],
};

// ─── SUNNLING — round, cheerful, three crown spikes ─────────────────────────
const SUNNLING: CreatureData = {
  id: 'sunnling', name: 'Sunnling', description: 'A cheerful hatchling bursting with warmth.',
  palette: { y: '#FFD966', e: '#2D2D2D', m: '#FF8C00', f: '#2D2D2D', h: '#FFF5AA', s: '#E8A000' },
  idleFrames: [
    [
      '................',
      '...y.y.y........',
      '...yyyyyyy......',
      '..yyyyyyyyy.....',
      '..yyyyyyyyyyy...',
      '..yhyyyyhyyy....',
      '..yyyyyyyyyy....',
      '..yyyeyyyeyyy...',
      '..yyyyyyyyyy....',
      '..yyymmmmyyy....',
      '..yyyyyyyyyy....',
      '...yyyyyyyyy....',
      '....yyyyyyy.....',
      '.....yyyyy......',
      '................',
      '................',
    ],
    [
      '................',
      '...y.y.y........',
      '...yyyyyyy......',
      '..yyyyyyyyy.....',
      '..yyyyyyyyyyy...',
      '..yhyyyyhyyy....',
      '..yyyyyyyyyy....',
      '..yyyffyyfyyy...',
      '..yyyyyyyyyy....',
      '..yyymmmmyyy....',
      '..yyyyyyyyyy....',
      '...yyyyyyyyy....',
      '....yyyyyyy.....',
      '.....yyyyy......',
      '................',
      '................',
    ],
  ],
  sleepFrames: [[
    '................',
    '...y.y.y........',
    '...yyyyyyy......',
    '..yyyyyyyyy.....',
    '..yyyyyyyyyyy...',
    '..yyyyyyyyyy....',
    '..yyyyyyyyyy....',
    '..yyyffyyfyyy...',
    '..yyyyyyyyyy....',
    '..yyyyyyyyyy....',
    '..yyyyyyyyyy....',
    '...yyyyyyyyy....',
    '....yyyyyyy.....',
    '.....yyyyy......',
    '................',
    '................',
  ]],
  eatFrames: [[
    '................',
    '...y.y.y........',
    '...yyyyyyy......',
    '..yyyyyyyyy.....',
    '..yyyyyyyyyyy...',
    '..yhyyyyhyyy....',
    '..yyyyyyyyyy....',
    '..yyyeyyyeyyy...',
    '..yyyyyyyyyy....',
    '..yyymmmmmmyyy..',
    '..yyyyyyyyyy....',
    '...yyyyyyyyy....',
    '....yyyyyyy.....',
    '.....yyyyy......',
    '................',
    '................',
  ]],
  happyFrames: [[
    '................',
    '...y.y.y........',
    '...yyyyyyy......',
    '..yyyyyyyyy.....',
    '..yyyyyyyyyyy...',
    '..yhyyyyhyyy....',
    '..yyyyyyyyyy....',
    '..yyyeyyyeyyy...',
    '..yyyyyyyyyy....',
    '..yymmmmmmmyy...',
    '..yyyyyyyyyy....',
    '...yyyyyyyyy....',
    '....yyyyyyy.....',
    '.....yyyyy......',
    '................',
    '................',
  ]],
};

// ─── GRUMBIT — blocky, stern, flat-edged ─────────────────────────────────────
const GRUMBIT: CreatureData = {
  id: 'grumbit', name: 'Grumbit', description: 'Gruff and sturdy. Don\'t mess with it.',
  palette: { b: '#7AABD4', e: '#0A2040', s: '#2E5A7A', m: '#3060A0', h: '#C0DDF0', f: '#0A2040' },
  idleFrames: [
    [
      '................',
      '..ssssssssss....',
      '..bbbbbbbbbb....',
      '..bbbbbbbbbb....',
      '..bbbbbbbbbb....',
      '..bssbbbbssb....',
      '..bbebbbbebb....',
      '..bbbbbbbbbb....',
      '..bbbssssbb.....',
      '..bbbbbbbbbb....',
      '..bbbbbbbbbb....',
      '..ssssssssss....',
      '................',
      '................',
      '................',
      '................',
    ],
    [
      '................',
      '..ssssssssss....',
      '..bbbbbbbbbb....',
      '..bbbbbbbbbb....',
      '..bbbbbbbbbb....',
      '..bssbbbbssb....',
      '..bbfbbbbfbb....',
      '..bbbbbbbbbb....',
      '..bbbssssbb.....',
      '..bbbbbbbbbb....',
      '..bbbbbbbbbb....',
      '..ssssssssss....',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
  sleepFrames: [[
    '................',
    '..ssssssssss....',
    '..bbbbbbbbbb....',
    '..bbbbbbbbbb....',
    '..bbbbbbbbbb....',
    '..bssbbbbssb....',
    '..bbfbbbbfbb....',
    '..bbbbbbbbbb....',
    '..bbbbbbbbbb....',
    '..bbbbbbbbbb....',
    '..bbbbbbbbbb....',
    '..ssssssssss....',
    '................',
    '................',
    '................',
    '................',
  ]],
  eatFrames: [[
    '................',
    '..ssssssssss....',
    '..bbbbbbbbbb....',
    '..bbbbbbbbbb....',
    '..bbbbbbbbbb....',
    '..bssbbbbssb....',
    '..bbebbbbebb....',
    '..bbbbbbbbbb....',
    '..bbbbbmbbbbb...',
    '..bbbbbbbbbb....',
    '..bbbbbbbbbb....',
    '..ssssssssss....',
    '................',
    '................',
    '................',
    '................',
  ]],
  happyFrames: [[
    '................',
    '..ssssssssss....',
    '..bbbbbbbbbb....',
    '..bbbbbbbbbb....',
    '..bbbbbbbbbb....',
    '..bssbbbbssb....',
    '..bbebbbbebb....',
    '..bbbbbbbbbb....',
    '..bbbsmmsbb.....',
    '..bbbbbbbbbb....',
    '..bbbbbbbbbb....',
    '..ssssssssss....',
    '................',
    '................',
    '................',
    '................',
  ]],
};

// ─── WISP — ghostly silhouette, huge eyes, tapers to a wispy tail ─────────────
const WISP: CreatureData = {
  id: 'wisp', name: 'Wisp', description: 'Ethereal and elusive. Sees right through you.',
  palette: { w: '#C4A0E8', e: '#3A1060', h: '#EDD8FF', f: '#3A1060', m: '#9060D0' },
  idleFrames: [
    [
      '................',
      '.....wwwww......',
      '....wwwwwwww....',
      '...wwwwwwwwww...',
      '...wwwwwwwwww...',
      '..wwwhwwwhwwww..',
      '..wwwwwwwwwwww..',
      '..wweewwweewww..',
      '..wweewwweewww..',
      '...wwwwwwwwww...',
      '....wwwwwwww....',
      '.....wwwwww.....',
      '......wwww......',
      '.......ww.......',
      '................',
      '................',
    ],
    [
      '................',
      '.....wwwww......',
      '....wwwwwwww....',
      '...wwwwwwwwww...',
      '...wwwwwwwwww...',
      '..wwwhwwwhwwww..',
      '..wwwwwwwwwwww..',
      '..wwffwwwffwww..',
      '..wwffwwwffwww..',
      '...wwwwwwwwww...',
      '....wwwwwwww....',
      '.....wwwwww.....',
      '......wwww......',
      '.......ww.......',
      '................',
      '................',
    ],
  ],
  sleepFrames: [[
    '................',
    '.....wwwww......',
    '....wwwwwwww....',
    '...wwwwwwwwww...',
    '...wwwwwwwwww...',
    '..wwwwwwwwwwww..',
    '..wwwwwwwwwwww..',
    '..wwffwwwffwww..',
    '..wwffwwwffwww..',
    '...wwwwwwwwww...',
    '....wwwwwwww....',
    '.....wwwwww.....',
    '......wwww......',
    '.......ww.......',
    '................',
    '................',
  ]],
  eatFrames: [[
    '................',
    '.....wwwww......',
    '....wwwwwwww....',
    '...wwwwwwwwww...',
    '...wwwwwwwwww...',
    '..wwwhwwwhwwww..',
    '..wwwwwwwwwwww..',
    '..wweewwweewww..',
    '..wweewwweewww..',
    '...wwwwmwwwww...',
    '....wwwwwwww....',
    '.....wwwwww.....',
    '......wwww......',
    '.......ww.......',
    '................',
    '................',
  ]],
  happyFrames: [[
    '................',
    '.....wwwww......',
    '....wwwwwwww....',
    '...wwwwwwwwww...',
    '...wwwwwwwwww...',
    '..wwwhwwwhwwww..',
    '..wwwwwwwwwwww..',
    '..weeewwweeeww..',
    '..weeewwweeeww..',
    '...wwwwwwwwww...',
    '....wwwwwwww....',
    '.....wwwwww.....',
    '......wwww......',
    '.......ww.......',
    '................',
    '................',
  ]],
};

const PUFFI: CreatureData = {
  id: 'puffi', name: 'Puffi', description: 'Round and bouncy. Loves to play.',
  palette: {
    p: '#FFB3C6',   // pink body
    e: '#2D2D2D',   // eye
    m: '#CC3355',   // mouth / smile
    f: '#2D2D2D',   // blink line
    s: '#FFCCD5',   // inner ear / highlight
  },
  idleFrames: [
    [
      '................',
      '..pp.....pp.....',
      '.ppsp...pspp....',
      '.pppppppppp.....',
      '.pppppppppppp...',
      '.ppepppppeppp...',
      '.ppepppppeppp...',
      '.pppppppppppp...',
      '.ppppmppmpppp...',
      '.ppppmmppppp....',
      '.pppppppppppp...',
      '..pppppppppp....',
      '..pppp..pppp....',
      '..pppp..pppp....',
      '................',
      '................',
    ],
    [
      '................',
      '..pp.....pp.....',
      '.ppsp...pspp....',
      '.pppppppppp.....',
      '.pppppppppppp...',
      '.ppfpppppfppp...',
      '.pppppppppppp...',
      '.pppppppppppp...',
      '.ppppmppmpppp...',
      '.ppppmmppppp....',
      '.pppppppppppp...',
      '..pppppppppp....',
      '..pppp..pppp....',
      '..pppp..pppp....',
      '................',
      '................',
    ],
  ],
  sleepFrames: [[
    '................',
    '..pp.....pp.....',
    '.ppsp...pspp....',
    '.pppppppppp.....',
    '.pppppppppppp...',
    '.ppfpppppfppp...',
    '.pppppppppppp...',
    '.pppppppppppp...',
    '.pppppppppppp...',
    '.pppppppppppp...',
    '.pppppppppppp...',
    '..pppppppppp....',
    '..pppp..pppp....',
    '..pppp..pppp....',
    '................',
    '................',
  ]],
  eatFrames: [[
    '................',
    '..pp.....pp.....',
    '.ppsp...pspp....',
    '.pppppppppp.....',
    '.pppppppppppp...',
    '.ppepppppeppp...',
    '.ppepppppeppp...',
    '.pppppppppppp...',
    '.ppppmmmmpppp...',
    '.pppppppppppp...',
    '.pppppppppppp...',
    '..pppppppppp....',
    '..pppp..pppp....',
    '..pppp..pppp....',
    '................',
    '................',
  ]],
  happyFrames: [[
    '................',
    '..pp.....pp.....',
    '.ppsp...pspp....',
    '.pppppppppp.....',
    '.pppppppppppp...',
    '.ppepppppeppp...',
    '.ppepppppeppp...',
    '.pppppppppppp...',
    '.pppmmmmmmppp...',
    '.pppppppppppp...',
    '.pppppppppppp...',
    '..pppppppppp....',
    '..pppp..pppp....',
    '..pppp..pppp....',
    '................',
    '................',
  ]],
};

const GRIMBLE: CreatureData = {
  id: 'grimble', name: 'Grimble', description: 'Five-spined grouch. Grumpy but mighty.',
  palette: {
    g: '#8BAAC4',   // blue-gray body
    e: '#1A2A3A',   // eye pupil
    h: '#5A7A90',   // heavy brow mark
    m: '#334455',   // frown pixel
    s: '#A8C4D8',   // spine tip highlight
  },
  idleFrames: [
    [
      '................',
      '..s.s.s.s.s.....',
      '..ggggggggg.....',
      '..gggggggggg....',
      '..ghggggghgg....',
      '..gegggggegg....',
      '..gggggggggg....',
      '..ggggmmgggg....',
      '..gggmggmggg....',
      '..gggggggggg....',
      '..gggggggggg....',
      '...gggggggg.....',
      '...gg....gg.....',
      '...gg....gg.....',
      '................',
      '................',
    ],
    [
      '................',
      '..s.s.s.s.s.....',
      '..ggggggggg.....',
      '..gggggggggg....',
      '..ghggggghgg....',
      '..gfgggggfgg....',
      '..gggggggggg....',
      '..ggggmmgggg....',
      '..gggmggmggg....',
      '..gggggggggg....',
      '..gggggggggg....',
      '...gggggggg.....',
      '...gg....gg.....',
      '...gg....gg.....',
      '................',
      '................',
    ],
  ],
  sleepFrames: [[
    '................',
    '..s.s.s.s.s.....',
    '..ggggggggg.....',
    '..gggggggggg....',
    '..ghggggghgg....',
    '..gfgggggfgg....',
    '..gggggggggg....',
    '..gggggggggg....',
    '..gggggggggg....',
    '..gggggggggg....',
    '..gggggggggg....',
    '...gggggggg.....',
    '...gg....gg.....',
    '...gg....gg.....',
    '................',
    '................',
  ]],
  eatFrames: [[
    '................',
    '..s.s.s.s.s.....',
    '..ggggggggg.....',
    '..gggggggggg....',
    '..ghggggghgg....',
    '..gegggggegg....',
    '..gggggggggg....',
    '..gggmmmmggg....',
    '..gggggggggg....',
    '..gggggggggg....',
    '..gggggggggg....',
    '...gggggggg.....',
    '...gg....gg.....',
    '...gg....gg.....',
    '................',
    '................',
  ]],
  happyFrames: [[
    '................',
    '..s.s.s.s.s.....',
    '..ggggggggg.....',
    '..gggggggggg....',
    '..gegggggegg....',
    '..gegggggegg....',
    '..gggggggggg....',
    '..gggmggmggg....',
    '..ggggmmgggg....',
    '..gggggggggg....',
    '..gggggggggg....',
    '...gggggggg.....',
    '...gg....gg.....',
    '...gg....gg.....',
    '................',
    '................',
  ]],
};

const LUMIX: CreatureData = {
  id: 'lumix', name: 'Lumix', description: 'A radiant being of pure joy.',
  palette: {
    l: '#FFD700',   // gold body
    e: '#FF6B00',   // fiery eye
    m: '#FF4400',   // mouth/smile accent
    s: '#FFF5AA',   // crown ray tip
    f: '#CC8800',   // blink line (darker gold)
  },
  idleFrames: [
    [
      '..s.s.s.s.s.....',
      '..lllllllll.....',
      '.lllllllllll....',
      '.lllllllllll....',
      '.lllellllelll...',
      '.lllellllelll...',
      '.lllllllllll....',
      '.lllmllllmlll...',
      '.llllmmmmlllll..',
      '.lllllllllll....',
      '..lllllllll.....',
      '...lllllll......',
      '..llll..llll....',
      '..llll..llll....',
      '................',
      '................',
    ],
    [
      '..s.s.s.s.s.....',
      '..lllllllll.....',
      '.lllllllllll....',
      '.lllllllllll....',
      '.lllfllllfll....',
      '.lllllllllll....',
      '.lllllllllll....',
      '.lllmllllmlll...',
      '.llllmmmmlllll..',
      '.lllllllllll....',
      '..lllllllll.....',
      '...lllllll......',
      '..llll..llll....',
      '..llll..llll....',
      '................',
      '................',
    ],
  ],
  sleepFrames: [[
    '..s.s.s.s.s.....',
    '..lllllllll.....',
    '.lllllllllll....',
    '.lllllllllll....',
    '.lllfllllfll....',
    '.lllllllllll....',
    '.lllllllllll....',
    '.lllllllllll....',
    '.lllllllllll....',
    '.lllllllllll....',
    '..lllllllll.....',
    '...lllllll......',
    '..llll..llll....',
    '..llll..llll....',
    '................',
    '................',
  ]],
  eatFrames: [[
    '..s.s.s.s.s.....',
    '..lllllllll.....',
    '.lllllllllll....',
    '.lllllllllll....',
    '.lllellllelll...',
    '.lllellllelll...',
    '.lllllllllll....',
    '.lllmmmmmllll...',
    '.lllllllllll....',
    '.lllllllllll....',
    '..lllllllll.....',
    '...lllllll......',
    '..llll..llll....',
    '..llll..llll....',
    '................',
    '................',
  ]],
  happyFrames: [[
    '..s.s.s.s.s.....',
    '..lllllllll.....',
    '.lllllllllll....',
    '.lllllllllll....',
    '.lllellllelll...',
    '.lllellllelll...',
    '.lllllllllll....',
    '.lllmllllmlll...',
    '.llllmmmmlllll..',
    '.lllllllllll....',
    '..lllllllll.....',
    '...lllllll......',
    '..llll..llll....',
    '..llll..llll....',
    '................',
    '................',
  ]],
};

const GLOOM: CreatureData = {
  id: 'gloom', name: 'Gloom', description: 'Tired eyes, heavy heart. Still here.',
  palette: {
    g: '#4A5568',   // dark gray body
    e: '#1A202C',   // sunken eye
    h: '#2D3748',   // heavy drooping lid
    m: '#2D3748',   // frown mouth
    t: '#718096',   // tear streak / drip
  },
  idleFrames: [
    [
      '................',
      '.....gggggg.....',
      '....gggggggg....',
      '...gggggggggg...',
      '..ghggggghgg....',
      '..ghggggghgg....',
      '..gegggggegg....',
      '..gggggggggg....',
      '..ggggmmgggg....',
      '..gggmggmggg....',
      '..tgggggggggt...',
      '..tgggggggggt...',
      '...tggggggt.....',
      '....tggggt......',
      '.....tggt.......',
      '......tt........',
    ],
    [
      '................',
      '.....gggggg.....',
      '....gggggggg....',
      '...gggggggggg...',
      '..ghggggghgg....',
      '..ghggggghgg....',
      '..ghggggghgg....',
      '..gggggggggg....',
      '..ggggmmgggg....',
      '..gggmggmggg....',
      '..tgggggggggt...',
      '..tgggggggggt...',
      '...tggggggt.....',
      '....tggggt......',
      '.....tggt.......',
      '......tt........',
    ],
  ],
  sleepFrames: [[
    '................',
    '.....gggggg.....',
    '....gggggggg....',
    '...gggggggggg...',
    '..ghggggghgg....',
    '..ghggggghgg....',
    '..ghggggghgg....',
    '..gggggggggg....',
    '..gggggggggg....',
    '..gggggggggg....',
    '..tgggggggggt...',
    '..tgggggggggt...',
    '...tggggggt.....',
    '....tggggt......',
    '.....tggt.......',
    '......tt........',
  ]],
  eatFrames: [[
    '................',
    '.....gggggg.....',
    '....gggggggg....',
    '...gggggggggg...',
    '..ghggggghgg....',
    '..gegggggegg....',
    '..gegggggegg....',
    '..gggggggggg....',
    '..gggmmmgggg....',
    '..gggggggggg....',
    '..tgggggggggt...',
    '..tgggggggggt...',
    '...tggggggt.....',
    '....tggggt......',
    '.....tggt.......',
    '......tt........',
  ]],
  happyFrames: [[
    '................',
    '.....gggggg.....',
    '....gggggggg....',
    '...gggggggggg...',
    '..gegggggegg....',
    '..gegggggegg....',
    '..gggggggggg....',
    '..gggggggggg....',
    '..gggmggmggg....',
    '..ggggmmgggg....',
    '..tgggggggggt...',
    '..tgggggggggt...',
    '...tggggggt.....',
    '....tggggt......',
    '.....tggt.......',
    '......tt........',
  ]],
};

const PHANTOM: CreatureData = {
  id: 'phantom', name: 'Phantom', description: '??? — A secret born of neglect.',
  palette: {
    p: '#4C1D95',   // deep violet body
    e: '#EDE9FE',   // glowing eye socket
    m: '#6D28D9',   // mouth/detail
    w: '#7C3AED',   // wave underbody
    s: '#A78BFA',   // shimmer highlight
  },
  idleFrames: [
    [
      '................',
      '..sp.....ps.....',
      '..ppppppppp.....',
      '.ppppppppppp....',
      '.ppppppppppp....',
      '.ppeepppeeppp...',
      '.ppeepppeeppp...',
      '.ppppppppppp....',
      '.pppmppmpppp....',
      '.ppppppppppp....',
      '..ppwpwpwppp....',
      '...pwpwpwpp.....',
      '....wpwpwp......',
      '.....wpwp.......',
      '......ww........',
      '................',
    ],
    [
      '................',
      '..sp.....ps.....',
      '..ppppppppp.....',
      '.ppppppppppp....',
      '.ppppppppppp....',
      '.ppeepppeeppp...',
      '.ppeepppeeppp...',
      '.ppppppppppp....',
      '.pppmppmpppp....',
      '.ppppppppppp....',
      '..ppwwpwpwpp....',
      '...pwpwwpwp.....',
      '....wpwpwpw.....',
      '.....wpwwp......',
      '......ww........',
      '................',
    ],
  ],
  sleepFrames: [[
    '................',
    '..sp.....ps.....',
    '..ppppppppp.....',
    '.ppppppppppp....',
    '.ppppppppppp....',
    '.ppeepppeeppp...',
    '.ppeepppeeppp...',
    '.ppppppppppp....',
    '.ppppppppppp....',
    '.ppppppppppp....',
    '..ppwpwpwppp....',
    '...pwpwpwpp.....',
    '....wpwpwp......',
    '.....wpwp.......',
    '......ww........',
    '................',
  ]],
  eatFrames: [[
    '................',
    '..sp.....ps.....',
    '..ppppppppp.....',
    '.ppppppppppp....',
    '.ppppppppppp....',
    '.ppeepppeeppp...',
    '.ppeepppeeppp...',
    '.ppppppppppp....',
    '.pppmmmmpppp....',
    '.ppppppppppp....',
    '..ppwpwpwppp....',
    '...pwpwpwpp.....',
    '....wpwpwp......',
    '.....wpwp.......',
    '......ww........',
    '................',
  ]],
  happyFrames: [[
    '................',
    '..sp.....ps.....',
    '..ppppppppp.....',
    '.ppppppppppp....',
    '.ppppppppppp....',
    '.ppeepppeeppp...',
    '.ppeepppeeppp...',
    '.ppppppppppp....',
    '.pppmppmppp.....',
    '.ppppmmmppppp...',
    '..ppwpwpwppp....',
    '...pwpwpwpp.....',
    '....wpwpwp......',
    '.....wpwp.......',
    '......ww........',
    '................',
  ]],
};

export const CREATURES: Record<CreatureId, CreatureData> = {
  egg: EGG, blobby: BLOBBY,
  sunnling: SUNNLING, grumbit: GRUMBIT, wisp: WISP,
  puffi: PUFFI, grimble: GRIMBLE,
  lumix: LUMIX, gloom: GLOOM, phantom: PHANTOM,
};

// ─── Lineage egg sprites ──────────────────────────────────────────────────────
// Each lineage gets a distinct egg shape + palette shown in StarterPicker
// and in-game while the pet is still an egg.

export const LINEAGE_EGG_FRAMES: Record<string, string[]> = {
  sunny: [
    // Wide & squat, single highlight, diagonal crack on left side
    '................',
    '................',
    '....aaaaaaaa....',
    '..aaaaaaaaaaaa..',
    '..aaabaaaaaaaa..',
    '..adaaaaaaaaaa..',
    '..aaaaaaaaaaaa..',
    '..aadaaaaaaaaa..',
    '..aaacccccaaaaa.',
    '..acccccccccaa..',
    '...aaaaaaaaaa...',
    '....aaaaaaaa....',
    '.....aaaaaa.....',
    '................',
    '................',
    '................',
  ],
  stormy: [
    // Tall & narrow, pointed top, zigzag lightning crack
    '.......aa.......',
    '......aaaa......',
    '.....aaaaaa.....',
    '....aabaaadaaaa.',
    '...aaaadaaaaaa..',
    '..aaaaaadaaaaa..',
    '..aaaadaaaaaa...',
    '..aaaaaadaaaaa..',
    '..aaaaaaaaaaaa..',
    '..aaccccccaaaa..',
    '..accccccccaa...',
    '...acccccca.....',
    '....aaaaaaaa....',
    '.....aaaaaa.....',
    '................',
    '................',
  ],
  misty: [
    // Round, single swirling crack curling from upper-left
    '................',
    '.....aaaaaa.....',
    '...aaaaaaaaaa...',
    '..aaadaaaaaaa...',
    '..aadaaaaaaaaa..',
    '..aaadaaaaaaa...',
    '..aaaadaaaaaa...',
    '..aaaaadaaaaa...',
    '..aaaaaadaaaa...',
    '..aacccccccaa...',
    '...accccccca....',
    '....aaaaaaaa....',
    '.....aaaaaa.....',
    '................',
    '................',
    '................',
  ],
};

export const LINEAGE_EGG_PALETTES: Record<string, Record<string, string>> = {
  sunny:  { a: '#FFE566', b: '#FFF8BB', c: '#CC8800', d: '#FF6600' },
  stormy: { a: '#7AABD4', b: '#C0DDF0', c: '#2E5A7A', d: '#0A1E30' },
  misty:  { a: '#C4A8D8', b: '#E8D8F8', c: '#6B4A8A', d: '#3A1A5C' },
};

// ─── Evolution tree ──────────────────────────────────────────────────────────

export function getEvolution(
  current: CreatureId,
  careScore: number,
  neglectCount: number,
  lineage?: string,
): CreatureId | null {
  switch (current) {
    case 'egg':
      if (lineage === 'stormy') return 'grumbit';
      if (lineage === 'misty')  return 'wisp';
      return 'sunnling';
    // legacy saves
    case 'blobby': {
      if (neglectCount >= 8) return 'phantom';
      const puffiThreshold = lineage === 'sunny' ? 50 : 60;
      return careScore >= puffiThreshold ? 'puffi' : 'grimble';
    }
    case 'sunnling':
      if (neglectCount >= 8) return 'grimble';
      return careScore >= 55 ? 'puffi' : 'grimble';
    case 'grumbit':
      return neglectCount >= 6 ? 'gloom' : 'grimble';
    case 'wisp':
      return 'phantom';
    case 'puffi':   return 'lumix';
    case 'grimble': return neglectCount >= 4 ? 'phantom' : 'gloom';
    default:        return null;
  }
}

// Hours of real time before evolution triggers
export const EVOLUTION_HOURS: Partial<Record<CreatureId, number>> = {
  egg:      0.083,  // ~5 min
  blobby:   24,     // legacy
  sunnling: 24,
  grumbit:  24,
  wisp:     24,
  puffi:    72,
  grimble:  72,
};
